version: '3'

services:
    sentinel-log:
        image: chaos.azurecr.io/sentinel-log:0.5
        ports:
        - "5142:5142"
        - "5142:5142/udp"
        volumes:
        - "/share/Container/rsyslog:/sentinel/rsyslog/remotelogs"
