version: '3'

services:
    sentinel-log:
        image: chaos.azurecr.io/sentinel-log:latest
        environment:
          PUID: 1001
          PGID: 100
        ports:
        - "5142:5142"
        - "5142:5142/udp"
        volumes:
        - "/share/remotelogs:/sentinel/rsyslog/remotelogs"
        - "/share/remotelogs/fluentd.conf:/sentinel/fluentd.conf"
